name: biome-check

on: 
  push:
    branches: 
      - "*"  
  pull_request: 

jobs:
  biome-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Biome Check
        run: |
          npx biome check || (
            echo "::error::🚨 Formatting issues detected! Please run 'npx biome format' locally to fix them." && exit 1
          )